<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class AddColumnslToDatatreeTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('datatree', function (Blueprint $table) {
                        $table->text('LegalBook')->nullable();
            $table->text('LegalPage')->nullable();
            $table->text('MapRef1')->nullable();
            $table->text('MapRef2')->nullable();
            $table->text('NeighborhoodName')->nullable();
            $table->text('ResidentialNeighborhoodName')->nullable();
            $table->text('SubNeighborhoodName')->nullable();
            $table->text('MacroNeighborhoodName')->nullable();
            $table->text('SchoolDistrict1')->nullable();
            $table->text('SchoolDistrict2')->nullable();
            $table->text('SchoolDistrict3')->nullable();
            $table->text('ElementarySchool')->nullable();
            $table->text('HighSchool')->nullable();
            $table->text('MiddleSchool')->nullable();
            $table->text('Zoning')->nullable();
            $table->text('LandUse')->nullable();
            $table->text('StateUse')->nullable();
            $table->text('CountyLandUse')->nullable();
            $table->text('SiteInfluence')->nullable();
            $table->text('ViewQuality')->nullable();
            $table->text('NumberOfBuildings')->nullable();
            $table->text('NumberOfResUnits')->nullable();
            $table->text('NumberOfbusCommUnits')->nullable();
            $table->text('UsableLot')->nullable();
            $table->text('UsableLotSize')->nullable();
            $table->text('LotShape')->nullable();
            $table->text('ACRES')->nullable();
            $table->text('LandSquareFootage')->nullable();
            $table->text('FrontFootage')->nullable();
            $table->text('DepthFootage')->nullable();
            $table->text('LegalLot')->nullable();
            $table->text('LegalBlock')->nullable();
            $table->text('WaterType')->nullable();
            $table->text('SewerType')->nullable();
            $table->text('FloodZoneCode')->nullable();
            $table->text('FloodMap')->nullable();
            $table->text('FloodMapDate')->nullable();
            $table->text('FloodPanel')->nullable();
            $table->text('CommunityName')->nullable();
            $table->text('InsideSFHA')->nullable();
            $table->text('SumOfAboveLivingSquareFootage')->nullable();
            $table->text('BuildingAreaSqft')->nullable();
            $table->text('GrossLivingArea')->nullable();
            $table->text('SumOfAdjustedGrossSquareFeet')->nullable();
            $table->text('SumOfGroundFloorSquareFeet')->nullable();
            $table->text('AdditionsSquareFeet')->nullable();
            $table->text('SumOfbasementSquareFeet')->nullable();
            $table->text('SumOfTotalRooms')->nullable();
            $table->text('SumOfBedRooms')->nullable();
            $table->text('FullBaths')->nullable();
            $table->text('BathroomsNew')->nullable();
            $table->text('HalfBaths')->nullable();
            $table->text('BathFixtures')->nullable();
            $table->text('NumberOfDiningRooms')->nullable();
            $table->text('NumberOfFamilyRooms')->nullable();
            $table->text('NumberOfOtherRooms')->nullable();
            $table->text('YearBuiltEffective')->nullable();
            $table->text('FireplaceIndicator')->nullable();
            $table->text('FirePlaceNumber')->nullable();
            $table->text('StoriesNumber')->nullable();
            $table->text('StoriesDescription')->nullable();
            $table->text('GarageType')->nullable();
            $table->text('ParkingType')->nullable();
            $table->text('GarageArea')->nullable();
            $table->text('ParkingSpaces')->nullable();
            $table->text('BasementType')->nullable();
            $table->text('BasementArea')->nullable();
            $table->text('FloorType')->nullable();
            $table->text('RoofType')->nullable();
            $table->text('RoofMaterialType')->nullable();
            $table->text('RoofFrame')->nullable();
            $table->text('Foundation')->nullable();
            $table->text('ConstructionType')->nullable();
            $table->text('ExteriorWall')->nullable();
            $table->text('Frame')->nullable();
            $table->text('PorchType')->nullable();
            $table->text('PorchSquareFootage')->nullable();
            $table->text('PatioType')->nullable();
            $table->text('PatioSquareFootage')->nullable();
            $table->text('Pool')->nullable();
            $table->text('PoolSquareFootage')->nullable();
            $table->text('AirConditioning')->nullable();
            $table->text('HeatType')->nullable();
            $table->text('HeatFuel')->nullable();
            $table->text('Electric')->nullable();
            $table->text('Style')->nullable();
            $table->text('Quality')->nullable();
            $table->text('Condition')->nullable();
            $table->text('TaxYear')->nullable();
            $table->text('TotalValueTaxable')->nullable();
            $table->text('PropertyTax')->nullable();
            $table->text('TaxArea')->nullable();
            $table->text('AppraisalDistrict')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('datatree', function (Blueprint $table) {
             $table->dropColumn('LegalBook');
             $table->dropColumn('LegalPage');
             $table->dropColumn('MapRef1');
             $table->dropColumn('MapRef2');
             $table->dropColumn('NeighborhoodName');
             $table->dropColumn('ResidentialNeighborhoodName');
             $table->dropColumn('SubNeighborhoodName');
             $table->dropColumn('MacroNeighborhoodName');
             $table->dropColumn('SchoolDistrict1');
             $table->dropColumn('SchoolDistrict2');
             $table->dropColumn('SchoolDistrict3');
             $table->dropColumn('ElementarySchool');
             $table->dropColumn('HighSchool');
             $table->dropColumn('MiddleSchool');
             $table->dropColumn('Zoning');
             $table->dropColumn('LandUse');
             $table->dropColumn('StateUse');
             $table->dropColumn('CountyLandUse');
             $table->dropColumn('SiteInfluence');
             $table->dropColumn('ViewQuality');
             $table->dropColumn('NumberOfBuildings');
             $table->dropColumn('NumberOfResUnits');
             $table->dropColumn('NumberOfbusCommUnits');
             $table->dropColumn('UsableLot');
             $table->dropColumn('UsableLotSize');
             $table->dropColumn('LotShape');
             $table->dropColumn('ACRES');
             $table->dropColumn('LandSquareFootage');
             $table->dropColumn('FrontFootage');
             $table->dropColumn('DepthFootage');
             $table->dropColumn('LegalLot');
             $table->dropColumn('LegalBlock');
             $table->dropColumn('WaterType');
             $table->dropColumn('SewerType');
             $table->dropColumn('FloodZoneCode');
             $table->dropColumn('FloodMap');
             $table->dropColumn('FloodMapDate');
             $table->dropColumn('FloodPanel');
             $table->dropColumn('CommunityName');
             $table->dropColumn('InsideSFHA');
             $table->dropColumn('SumOfAboveLivingSquareFootage');
             $table->dropColumn('BuildingAreaSqft');
             $table->dropColumn('GrossLivingArea');
             $table->dropColumn('SumOfAdjustedGrossSquareFeet');
             $table->dropColumn('SumOfGroundFloorSquareFeet');
             $table->dropColumn('AdditionsSquareFeet');
             $table->dropColumn('SumOfbasementSquareFeet');
             $table->dropColumn('SumOfTotalRooms');
             $table->dropColumn('SumOfBedRooms');
             $table->dropColumn('FullBaths');
             $table->dropColumn('BathroomsNew');
             $table->dropColumn('HalfBaths');
             $table->dropColumn('BathFixtures');
             $table->dropColumn('NumberOfDiningRooms');
             $table->dropColumn('NumberOfFamilyRooms');
             $table->dropColumn('NumberOfOtherRooms');
             $table->dropColumn('YearBuiltEffective');
             $table->dropColumn('FireplaceIndicator');
             $table->dropColumn('FirePlaceNumber');
             $table->dropColumn('StoriesNumber');
             $table->dropColumn('StoriesDescription');
             $table->dropColumn('GarageType');
             $table->dropColumn('ParkingType');
             $table->dropColumn('GarageArea');
             $table->dropColumn('ParkingSpaces');
             $table->dropColumn('BasementType');
             $table->dropColumn('BasementArea');
             $table->dropColumn('FloorType');
             $table->dropColumn('RoofType');
             $table->dropColumn('RoofMaterialType');
             $table->dropColumn('RoofFrame');
             $table->dropColumn('Foundation');
             $table->dropColumn('ConstructionType');
             $table->dropColumn('ExteriorWall');
             $table->dropColumn('Frame');
             $table->dropColumn('PorchType');
             $table->dropColumn('PorchSquareFootage');
             $table->dropColumn('PatioType');
             $table->dropColumn('PatioSquareFootage');
             $table->dropColumn('Pool');
             $table->dropColumn('PoolSquareFootage');
             $table->dropColumn('AirConditioning');
             $table->dropColumn('HeatType');
             $table->dropColumn('HeatFuel');
             $table->dropColumn('Electric');
             $table->dropColumn('Style');
             $table->dropColumn('Quality');
             $table->dropColumn('Condition');
             $table->dropColumn('TaxYear');
             $table->dropColumn('TotalValueTaxable');
             $table->dropColumn('PropertyTax');
             $table->dropColumn('TaxArea');
             $table->dropColumn('AppraisalDistrict');
        });
    }
}
